(in-package #:sys.int)

(defconstant +tag-even-fixnum+  #b0000)
(defconstant +tag-cons+         #b0001)
(defconstant +tag-symbol+       #b0010)
(defconstant +tag-array-header+ #b0011)
(defconstant +tag-std-instance+ #b0100)
;;(defconstant +tag-+  #b0101)
;;(defconstant +tag-+  #b0110)
(defconstant +tag-array-like+   #b0111)
(defconstant +tag-odd-fixnum+   #b1000)
;;(defconstant +tag-+  #b1001)
(defconstant +tag-character+    #b1010)
;;(defconstant +tag-+  #b1011)
(defconstant +tag-function+     #b1100)
;;(defconstant +tag-+  #b1101)
(defconstant +tag-unbound-value+  #b1110)
;;(defconstant +tag-+  #b1111)

(defconstant +array-type-t+ 0)
(defconstant +array-type-base-char+ 1)
(defconstant +array-type-character+ 2)
(defconstant +array-type-unsigned-byte-8+ 6)
(defconstant +array-type-unsigned-byte-16+ 7)
(defconstant +array-type-unsigned-byte-32+ 8)
(defconstant +array-type-unsigned-byte-64+ 9)
(defconstant +array-type-bignum+ 25)
(defconstant +array-type-stack-group+ 30)
(defconstant +array-type-struct+ 31)

(defconstant +function-type-function+ 0)
(defconstant +function-type-closure+ 1)
