;;; -*- Lisp -*-

;; load preferences if asdf::*load-preference-files* is true
(load "script-support")
(load "../asdf")
(in-package #:common-lisp-user)

(defvar *test6* nil)

(exit-on-error
 (setf asdf:*central-registry* '(*default-pathname-defaults*))
 (defmethod asdf:preference-file-for-system/operation
           ((system (eql (asdf:find-system 'test1))) operation)
  (merge-pathnames (make-pathname :name "test1" :type "preferences")))
 (setf asdf::*load-preference-files* t)
 (asdf:operate 'asdf:load-op 'test1)
 (assert (eq *test6* :yes)))



