(in-package :png-read)

(defclass png-state ()
  ((file :accessor png-file :initform nil)
   (finished :accessor finished :initform nil)
   (width :accessor width)
   (height :accessor height)
   (bit-depth :accessor bit-depth)
   (colour-type :accessor colour-type)
   (compression :accessor compression)
   (filter-method :accessor filter-method)
   (interlace-method :accessor interlace-method)
   (pallete :accessor pallete)
   (datastream :accessor datastream :initform nil)
   (image-data :accessor image-data)
   (index-data :accessor index-data :initform nil)
   ;ancillaries
   (postprocess-ancillaries :accessor postprocess-ancillaries :initform nil)
   (transparency :accessor transparency :initform nil)
   (gamma :accessor gamma :initform nil)
   (significant-bits :accessor significant-bits :initform nil)
   (rendering-intent :accessor rendering-intent :initform nil)
   (textual-data :accessor textual-data :initform nil)
   (preferred-background :accessor preferred-background :initform nil)
   (image-histogram :accessor image-histogram :initform nil)
   (physical-dimensions :accessor physical-dimensions :initform nil)
   (last-modification :accessor last-modification :initform nil)))

(defvar *png-state* nil)