;;; -*- Lisp -*-

;;; make sure we get a missing-component error

(in-package :asdf-test)

(handler-case
    (asdf:oos 'asdf:load-op 'system-does-not-exist)
  (asdf:missing-component-of-version (c)
    (declare (ignore c))
    (error "Should not have gotten 'missing-component-of-version, dang"))
  (asdf:missing-component (c)
    (format t "got missing-component as expected: - ~%~A~%" c))
  (:no-error (c)
    (declare (ignore c))
    (error "should have failed, oops")))
